name: Read Hello.txt and Output Content

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  read-hello-file:
    runs-on: ubuntu-latest  # The job will run on an Ubuntu machine
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # This checks out the code from the repository


